version: '2'
services:
  kitawo-telegram:
    build: .
    expose:
      - 3000
    environment:
      VIRTUAL_PORT: 3000
      VIRTUAL_HOST: "${TELEGRAM_VIRTUAL_HOST}"
      LETSENCRYPT_HOST: "${TELEGRAM_LETSENCRYPT_HOST}"
      LETSENCRYPT_EMAIL: "${TELEGRAM_LETSENCRYPT_EMAIL}"
      PRISMA_SECRET: "${PRISMA_SECRET}"
      PRISMA_HOST: "${PRISMA_HOST}"
      TELEGRAM_SECRET: "${TELEGRAM_SECRET}"
      TELEGRAM_WEBHOOK: "${TELEGRAM_WEBHOOK}"
      TELEGRAM_SECRET_PATH: "${TELEGRAM_SECRET_PATH}"
      CHAT_ID: "${CHAT_ID}"
networks:
  default:
    external:
      name: nginx-net

